### ISSUE TITLE
Where do one start?

### ISSUE THREAD

**Issue by daniejstriata** [Fraudmarc/fraudmarc-ce#17]
Sorry. I'm not sure where to start. Does this require a dedicated AWS server? The wiki starts with installing git. Do I need to install a host for this running on AWS or can I use my own host running elsewhere?

I see someone else ask a similar question and the ticket was closed without an answer.

**Comment by kcolemangt** [comment]
Please use the issue tracker for working on issues and features.

Your question is answered in the [README](https://github.com/Fraudmarc/fraudmarc-ce/blob/master/README.md), [INSTALL](https://github.com/Fraudmarc/fraudmarc-ce/blob/master/INSTALL.md) instructions or [INSTALL-ADVANCED](https://github.com/Fraudmarc/fraudmarc-ce/blob/master/INSTALL-ADVANCED.md).

Usage discussion is welcome on the [DMARC Community Forum](https://community.fraudmarc.com/).
