### ISSUE TITLE
I dont see process lambda triggers

### ISSUE THREAD

**Issue by dporr** [Fraudmarc/fraudmarc-ce#19]
Hi, I installed fraudmarc-ce using the easy install (docker container).
Currently I confirmed 2 lambdas where created, and the mails get to my s3, but in the process function histogram I don't see its being invoked and no records from dmarc reports are being agreggated to my RDS (The receive functions its gettig executed as I see the "analyze logs" under lambda details)

Where can I look for the process lambda invocations?

**Comment by kcolemangt** [comment]
This issue has been resolved by the changes in PR #71, which significantly streamlines the build and deployment process, reducing setup time to just a few minutes.
