### ISSUE TITLE
Failed to invoke DRE update bulk lambda: ResourceNotFoundException

### ISSUE THREAD

**Issue by Antyrael** [Fraudmarc/fraudmarc-ce#21]
Hi,

First of all, thanks for providing this free product!

Unfortunately though, I'm getting the following error when I check the logs of the fraudmarc-ce-receive Lambda function:
```
2019/09/23 09:17:07 spf: {obscurity.eu pass pl7hnthl513hnf7roujptqi70fhb6oe3qv9k6v81 3}
**2019/09/23 09:17:08 Failed to invoke DRE update bulk lambda: ResourceNotFoundException: Functions from 'eu-west-1' are not reachable in this region ('us-east-1')**
status code: 404, request id: 123f28d9-4505-4ff8-9148-767272a685b3
2019/09/23 09:17:08 q.Records[0].SES.Mail.MessageID: pl7hnthl513hnf7roujptqi70fhb6oe3qv9k6v81
END RequestId: f1cedee7-713b-422c-812e-2701cee9d3af
REPORT RequestId: f1cedee7-713b-422c-812e-2701cee9d3af Duration: 609.25 ms Billed Duration: 700 ms Memory Size: 1536 MB Max Memory Used: 60 MB Init Duration: 258.62 ms
XRAY TraceId: 1-5d888d92-630c43a0f0c7a828013b0eb8 SegmentId: 0dc42e9e77aeaedd Sampled: false
```

I created everything in eu-west-1 (Ireland): the Lambda functions, RDS database and S3 bucket using the provided basic installation instructions. So I can't figure out what's going wrong here.
What can I do to fix this? I don't want my resources in the US for performance reasons.

PS: I tried to register an account on your community website 2 days ago, but I'm just not receiving the activation e-mail. I tried 2 e-mail addresses, checked the Spam folder both times.

**Comment by Antyrael** [comment]
Never mind, it's obvious to me now that this project is no longer maintained or supported.

**Comment by kcolemangt** [comment]
@Antyrael Please contact us on our main company page and we'll help you run CE in the EU.

**Comment by kcolemangt** [comment]
@Antyrael v2 in PR #71 easily deploys to EU regions.
