### ISSUE TITLE
Unable to create db.t2.micro database

### ISSUE THREAD

**Issue by BriMan83** [Fraudmarc/fraudmarc-ce#50]
Following down the basic instructions in INSTALL.md, and got everything set up through the docker deployment (the end of step 2).

When I run the command `sudo docker run -it --env-file env.list --env-file installer/env.list fraudmarc/fraudmarc-ce-install`, it generates the error `An error occurred (InsufficientDBInstanceCapacity) when calling the CreateDBInstance operation: Cannot create a db.t2.micro database instance because there are no availability zones with sufficient capacity for non-VPC and storage type : gp2 for db.t2.micro. Please try the request again at a later time.`

I'm trying to execute this using us-west-2 if that makes any difference.

**Comment by jwrichards** [comment]
It seems to have errored out entirely -- No lambdas, s3 buckets, or anything else appears to have been created, and the only output from running Docker was:

`An error occurred (InvalidParameterCombination) when calling the CreateDBInstance operation: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t2.micro, Engine=postgres, EngineVersion=13.3, LicenseModel=postgresql-license. For supported combinations of instance class and database engine version, see the documentation.`

**Comment by kcolemangt** [comment]
@BriMan83 @jwrichards PR #71 streamlined the build and deployment process, reducing setup time to just a few minutes.
