### ISSUE TITLE
Advanced Install and APEX

### ISSUE THREAD

**Issue by moorereason** [Fraudmarc/fraudmarc-ce#67]
The `INSTALL_ADVANCED.md` [contains instructions](https://github.com/Fraudmarc/fraudmarc-ce/blob/master/INSTALL-ADVANCED.md?plain=1#L130) under the Lambda section:

```md
2. Follow the [APEX](http://apex.run/) instructions to install apex.
```

That URL is no longer active.  Is APEX still in use?  Where do we find it today?

**Comment by kcolemangt** [comment]
https://github.com/Fraudmarc/apex

**Comment by kcolemangt** [comment]
#71 significantly streamlines the build and deployment process, reducing setup time to just a few minutes.
