### ISSUE TITLE
AWS estimates

### ISSUE THREAD

**Issue by paulunlmtd** [Fraudmarc/fraudmarc-ce#73]
AWS estimates need updating, I believe. Recent price changes for IPs and the requirement for an always-on t3.micro instance make the costs well-above estimates.

**Comment by kcolemangt** [comment]
What's your estimate?

**Comment by paulunlmtd** [comment]
Running it about a month now, and it looks like ~$21.

**Comment by kcolemangt** [comment]
Interesting. Please share the cost breakdown by service and the number of domains and their monthly DMARC data volume.

**Comment by paulunlmtd** [comment]
1 domain - 129,456 total.
**AWS** 

- API Gateway: $0.00
- Route 53: $0.50
- Secrets Manager: $0.72
- EC2-Instance: $7.00
- RDS: $12.84

**Comment by kcolemangt** [comment]
It seems you're not on the RDS free tier.

I looked at one of our installations and noticed a possible bug in NAT ASG provider using a second public IP. I've reported in [cdk-nat-asg-provider](https://github.com/fonzcastellanos/cdk-nat-asg-provider/issues/3). If cost-saving is a priority over automatic redeployment on instance failure, you could save a few dollars by changing this:

```
natGatewayProvider: new NatAsgProvider({
  instanceType: new cdk.aws_ec2.InstanceType('t3.micro'),
}),
```

to

```
natGatewayProvider: cdk.aws_ec2.NatProvider.instanceV2({
  instanceType: new cdk.aws_ec2.InstanceType('t3.micro'),
}),
```

in `cdk/lib/cdk-app.ts`.

The installation I checked is not eligible for the free tier. It costs $28 and processes DMARC data for multiple companies, with a combined monthly email volume of about 60 million.

**Comment by paulunlmtd** [comment]
Got it. Thank you so much for your assistance. Truly appreciate that Fraudmarc even has a community edition. I work for a non-profit and, yes, we are very cost-conscious.
